version: 1
formatters:
  simple:
    format: '%(asctime)s  - %(levelname)s - %(message)s'
  precise:
    format: '[%(asctime)s] [%(levelname)s]  [%(ip)s]  [%(username)s] %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  console_err:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stderr
  file:
    class : logging.handlers.RotatingFileHandler
    formatter: precise
    filename: fortress.log
    level: DEBUG
    maxBytes: 1024
    backupCount: 3

loggers:
  simpleExample:
    level: INFO
    handlers: [console]
    propagate: yes
  filelog:
    level: DEBUG
    handlers: [file]
    propagate: yes
#root:
#  level: DEBUG
#  handlers: [console_err]