# Generated by Django 2.1.8 on 2019-04-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soft',
            name='describe',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
    ]
