# Generated by Django 2.1.8 on 2019-04-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft', '0002_auto_20190417_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='soft',
            name='soft_icon',
            field=models.ImageField(default='', height_field='url_height', upload_to='soft_icons', width_field='url_width'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soft',
            name='url_height',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AddField(
            model_name='soft',
            name='url_width',
            field=models.PositiveIntegerField(default=75),
        ),
    ]
