# Generated by Django 2.1.8 on 2019-04-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft', '0003_auto_20190417_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soft',
            name='url_height',
        ),
        migrations.RemoveField(
            model_name='soft',
            name='url_width',
        ),
        migrations.AlterField(
            model_name='soft',
            name='soft_icon',
            field=models.ImageField(upload_to='soft_icons/'),
        ),
    ]
