# Generated by Django 2.1.8 on 2019-04-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft', '0007_serversoft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serversoft',
            name='status',
            field=models.IntegerField(choices=[(0, '未安装'), (1, '正在安装'), (2, '安装出错'), (3, '已安装'), (4, '正在卸载'), (5, '卸载出错'), (5, '卸载完成')], verbose_name='状态'),
        ),
    ]
