# Generated by Django 2.0.5 on 2019-04-16 05:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleServerGroup',
            fields=[
                ('uuid', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('describe', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'ansible主机组',
                'verbose_name': 'ansible主机组',
            },
        ),
    ]
