# Generated by Django 2.0.5 on 2019-04-16 05:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetOperationLog',
            fields=[
                ('uuid', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField(null=True, verbose_name='修改详情')),
            ],
            options={
                'verbose_name_plural': '资产日志',
                'verbose_name': '资产日志',
            },
        ),
        migrations.CreateModel(
            name='Crond',
            fields=[
                ('uuid', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('describe', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('uuid', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20, verbose_name='机房名称')),
                ('type', models.IntegerField(blank=True, choices=[(0, 'IDC机房'), (1, '公有云'), (2, '私有云')], null=True, verbose_name='机房类型')),
                ('address', models.CharField(max_length=20, verbose_name='机房位置')),
                ('contack_name', models.CharField(max_length=10, verbose_name='联系人')),
                ('contack_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('contack_qq', models.CharField(blank=True, max_length=10, null=True, verbose_name='联系qq')),
                ('contack_mail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='联系邮箱')),
                ('bandwidth', models.CharField(blank=True, max_length=10, null=True, verbose_name='机房带宽')),
            ],
            options={
                'verbose_name_plural': 'IDC列表',
                'verbose_name': 'IDC列表',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('uuid', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('check_time', models.DateTimeField(auto_now_add=True, verbose_name='检查时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '服务标签',
                'verbose_name': '服务标签',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uuid', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='名称')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='介绍')),
                ('check_time', models.DateTimeField(auto_now_add=True, verbose_name='检查时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '业务组',
                'verbose_name': '业务名称',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('uuid', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='使用状态')),
                ('system', models.CharField(blank=True, max_length=20, verbose_name='操作系统')),
                ('location', models.CharField(blank=True, max_length=30, null=True, verbose_name='机架位置')),
                ('check_time', models.DateTimeField(auto_now_add=True, verbose_name='检查时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mod_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('ssh_port', models.IntegerField(default=22, verbose_name='SSH端口')),
                ('manufacturer', models.CharField(blank=True, max_length=20, verbose_name='厂商')),
                ('productname', models.CharField(blank=True, max_length=30, verbose_name='产品型号')),
                ('service_tag', models.CharField(blank=True, max_length=80, null=True, verbose_name='序列号')),
                ('cpu_model', models.CharField(blank=True, max_length=50, verbose_name='CPU型号')),
                ('cpu_nums', models.CharField(blank=True, max_length=50, verbose_name='CPU线程数')),
                ('cpu_groups', models.CharField(blank=True, max_length=50, null=True, verbose_name='CPU物理核数')),
                ('mem', models.CharField(blank=True, max_length=100, verbose_name='内存大小')),
                ('disk', models.CharField(blank=True, max_length=300, verbose_name='硬盘大小')),
                ('hostname', models.CharField(blank=True, max_length=30, verbose_name='主机名')),
                ('ip2', models.CharField(blank=True, max_length=50, null=True, verbose_name='其他IP地址')),
                ('comment', models.TextField(blank=True, default='', max_length=128, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '主机列表',
                'verbose_name': '主机列表',
            },
        ),
        migrations.CreateModel(
            name='ServerLog',
            fields=[
                ('uuid', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('describe', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='ServerUser',
            fields=[
                ('uuid', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('priority', models.IntegerField(default=10, verbose_name='优先权限')),
                ('protocol', models.CharField(choices=[('ssh', 'ssh'), ('rdp', 'rdp')], default='ssh', max_length=16, verbose_name='协议')),
                ('auto_push', models.BooleanField(default=True, verbose_name='Auto push')),
                ('sudo', models.TextField(default='/bin/whoami', verbose_name='Sudo')),
                ('shell', models.CharField(default='/bin/bash', max_length=64, verbose_name='Shell')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('uuid', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('describe', models.TextField(blank=True, null=True)),
                ('modify_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '应用服务',
                'verbose_name': '应用服务',
            },
        ),
    ]
