# Generated by Django 2.0.5 on 2019-04-16 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0001_initial'),
        ('ansible_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverlog',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建用户'),
        ),
        migrations.AddField(
            model_name='serverlog',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Server', verbose_name='主机ID'),
        ),
        migrations.AddField(
            model_name='server',
            name='ansible_group',
            field=models.ManyToManyField(blank=True, to='ansible_api.AnsibleServerGroup', verbose_name='ansible组'),
        ),
        migrations.AddField(
            model_name='server',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建用户'),
        ),
        migrations.AddField(
            model_name='server',
            name='idc_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.IDC', verbose_name='所属机房'),
        ),
        migrations.AddField(
            model_name='server',
            name='label',
            field=models.ManyToManyField(blank=True, to='assets.Label', verbose_name='服务标签'),
        ),
        migrations.AddField(
            model_name='server',
            name='project',
            field=models.ManyToManyField(blank=True, to='assets.Project', verbose_name='业务组'),
        ),
        migrations.AddField(
            model_name='server',
            name='services',
            field=models.ManyToManyField(blank=True, to='assets.Service', verbose_name='应用'),
        ),
        migrations.AddField(
            model_name='server',
            name='ssh_user',
            field=models.ManyToManyField(blank=True, to='assets.ServerUser', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='crond',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建用户'),
        ),
        migrations.AddField(
            model_name='assetoperationlog',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Server', verbose_name='主机ID'),
        ),
    ]
