# Generated by Django 2.1.8 on 2019-04-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft', '0002_auto_20190417_1420'),
        ('assets', '0003_serverlog_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='soft',
            field=models.ManyToManyField(blank=True, to='soft.Soft', verbose_name='应用'),
        ),
    ]
