# Generated by Django 2.1.8 on 2019-04-17 18:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('soft', '0005_auto_20190417_1823'),
        ('assets', '0004_server_soft'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerSoft',
            fields=[
                ('uuid', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('status', models.IntegerField(choices=[(0, '未安装'), (1, '正在安装'), (2, '安装出错')], verbose_name='状态')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Server', verbose_name='主机')),
                ('soft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soft.Soft', verbose_name='软件')),
            ],
        ),
    ]
