# Generated by Django 2.1.8 on 2019-04-18 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_remove_server_soft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serversoft',
            name='server',
        ),
        migrations.RemoveField(
            model_name='serversoft',
            name='soft',
        ),
        migrations.DeleteModel(
            name='ServerSoft',
        ),
    ]
