# Generated by Django 2.1.8 on 2019-04-22 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20190418_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='idc',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
    ]
