# Generated by Django 2.1.8 on 2019-04-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20190416_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ansibleplaybook',
            name='is_shared',
            field=models.BooleanField(blank=True, default=False, verbose_name='是否共享'),
        ),
        migrations.AlterField(
            model_name='ansiblescript',
            name='is_shared',
            field=models.BooleanField(blank=True, default=False, verbose_name='是否共享'),
        ),
        migrations.AlterField(
            model_name='files',
            name='is_shared',
            field=models.BooleanField(blank=True, default=False, verbose_name='是否共享'),
        ),
    ]
