# Generated by Django 2.0.5 on 2019-04-16 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authorize', '0001_initial'),
        ('users', '0001_initial'),
        ('assets', '0002_auto_20190416_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='authnode',
            name='user_name',
            field=models.ForeignKey(help_text='用户', max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='authnode_user', to=settings.AUTH_USER_MODEL, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='authgroupnode',
            name='department_name',
            field=models.ForeignKey(help_text='部门', max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='authdepnode_user', to='users.Department', verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='authgroupnode',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authdepnode_node', to='assets.Server', verbose_name='主机'),
        ),
        migrations.AddField(
            model_name='auth_group',
            name='group_user',
            field=models.ManyToManyField(blank=True, related_name='user_auth_group', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
    ]
